# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-06 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Online',
        ),
    ]
